const GET_POSTS = "GET_POSTS";
const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
const GET_POSTS_ERROR = "GET_POSTS_ERROR";

const POST_POSTS = "POST_POSTS";
const POST_POSTS_SUCCESS = "POST_POSTS_SUCCESS";
const POST_POSTS_ERROR = "POST_POSTS_ERROR";

export {
  GET_POSTS,
  GET_POSTS_SUCCESS,
  GET_POSTS_ERROR,
  POST_POSTS,
  POST_POSTS_ERROR,
  POST_POSTS_SUCCESS
};
